name: Get remote package version
description: Retrieves semantic version from remote repository

inputs:
  package-name:
    description: The npm package name to look up
    required: true

outputs:
  version:
    description: The remote package version
    value: ${{ steps.version.outputs.result }}

runs:
  using: composite
  steps:
    - name: Read version
      id: version
      shell: bash
      run: echo "result=$(npm view '${{ inputs.package-name }}' version)" >> "$GITHUB_OUTPUT"
