name: Release
description: Publishes a package to NPM and creates and pushes a new tag

inputs:
  package-path:
    description: The path to the package directory
    required: true
  npm-token:
    description: The npm authentication token
    required: true

runs:
  using: composite
  steps:
    - name: Get local package information
      id: local
      uses: ./.github/actions/npm/get-package-information
      with:
        working-directory: ${{ inputs.package-path }}

    - name: Get remote version
      id: remote
      uses: ./.github/actions/npm/get-remote-version
      with:
        package-name: ${{ steps.local.outputs.name }}

    - name: Publish to npm
      if: steps.local.outputs.version != steps.remote.outputs.version
      uses: ./.github/actions/npm/publish
      with:
        package-path: ${{ inputs.package-path }}
        npm-token: ${{ inputs.npm-token }}

    - name: Create and push tag
      if: steps.local.outputs.version != steps.remote.outputs.version
      uses: ./.github/actions/git/create-and-push-tag
      with:
        package-name: ${{ steps.local.outputs.name }}
        package-version: ${{ steps.local.outputs.version }}
