name: Release base tsconfig

on: workflow_dispatch

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: aspithost/actions/.github/workflows/node-release.yml@v2
    permissions:
      contents: write
      id-token: write
    with:
      working-directory: packages/base
