name: Get local package.json version
description: Retrieves semantic version from package.json

inputs:
  working-directory:
    description: Path to the package directory
    required: true

outputs:
  name:
    description: The name from package.json
    value: ${{ steps.package-info.outputs.name }}
  version:
    description: The version from package.json
    value: ${{ steps.package-info.outputs.version }}

runs:
  using: composite
  steps:
    - name: Read package info
      id: package-info
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "name=$(node -p 'require("./package.json").name')" >> "$GITHUB_OUTPUT"
        echo "version=$(node -p 'require("./package.json").version')" >> "$GITHUB_OUTPUT"
